name: "PHP Lint"

on: [pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Get versions
        run: |
          which php
          php --version

      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php,**.js,**.css"
          phpcs_path: ./vendor/bin/phpcs
          standard: phpcs.xml