name: "PHP Lint"

on: [pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - uses: thenabeel/action-phpcs@v8
        with:
          phpcs_path: phpcs
          standard: phpcs.xml