name: "PHP Lint"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # PHP 8 will throw PHP Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in ...
      - uses: nanasess/setup-php@v3
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php,**.js,**.css"
          phpcs_path: ./vendor/bin/phpcs
          standard: phpcs.xml